apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.xgeeks.org/team: idp_training
  backstage.io/kubernetes-id: xgeeks-nestjs-api

namespace: idp-dev
# namespace: xgeeks-nestjs-api-idp_training-dev

resources:
- ../../base
- ingress.yaml

  # ATENTION name = image.name NOT name = spec.containers[0].name
images:
- name: ghcr.io/xgeekshq/xgeeks-nestjs-api
  newTag: 48518f4

replicas:
- count: 1
  name: xgeeks-nestjs-api
